services:
    ollama-service:
        image: ollama/ollama
        ports:
            - 11434:11434
        volumes:
            - ollama:/root/.ollama
        restart: always

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        ports:
            - "15000:8080"
        volumes:
            - open-webui:/app/backend/data
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    ollama: {}
    open-webui: {}
